spring:
  profiles:
    active: dev
  application:
    name: draw-guess-java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${draw.db.url}
    username: ${draw.db.username}
    password: ${draw.db.password}
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 10000
  data:
    redis:
      host: 47.99.113.58
      password: asd1245+asd
      port: 6379
  jpa:
    generate-ddl: true
    show-sql: false
  jackson:
    default-property-inclusion: non_null
oss:
  region: cn-shanghai
  endpoint: https://oss-cn-shanghai.aliyuncs.com
  domain: https://oss.guetzjb.cn/
  bucket: oss-pai-hdzvw7bjvj2tv17tu8-cn-shanghai
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: drawauth
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
server:
  port: 8866