/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    AInput: typeof import('ant-design-vue/es')['Input']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    AStatisticCountdown: typeof import('ant-design-vue/es')['StatisticCountdown']
    Hall: typeof import('./../src/views/hall/index.vue')['default']
    IInput: typeof import('./../src/components/IInput/index.vue')['default']
    Index: typeof import('./../src/views/index/index.vue')['default']
    MessageBox: typeof import('./../src/views/index/MessageBox.vue')['default']
    OnlineUserBar: typeof import('./../src/components/OnlineUserBar.vue')['default']
    RainbowButton: typeof import('./../src/components/RainbowButton/index.vue')['default']
    RippleButton: typeof import('./../src/components/RippleButton/index.vue')['default']
    RoomTopInfo: typeof import('./../src/components/RoomTopInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettlementPopup: typeof import('./../src/views/index/SettlementPopup.vue')['default']
    ShimmerButton: typeof import('./../src/components/ShimmerButton/index.vue')['default']
    TestPage: typeof import('./../src/views/TestPage/index.vue')['default']
  }
}
